import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../hooks/useAuth';
import { Search, Plus, Pencil, UserX, Eye } from 'lucide-react';

const blank={first_name:'',last_name:'',email:'',phone:'',date_of_birth:'',address:'',gender:'',membership_date:new Date().toISOString().slice(0,10),status:'active'};
export default function Members(){
 const {user}=useAuth(); const admin=user?.role==='admin';
 const [rows,setRows]=useState<any[]>([]); const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [modal,setModal]=useState(false); const [editing,setEditing]=useState<any|null>(null); const [form,setForm]=useState<any>(blank); const [error,setError]=useState('');
 const load=()=>api.members(`?search=${encodeURIComponent(search)}&status=${status}`).then(r=>setRows(r.data)).catch(e=>setError(e.message));
 useEffect(()=>{load()},[search,status]);
 function edit(m:any){setEditing(m);setForm({...m,date_of_birth:m.date_of_birth?.slice(0,10)||'',membership_date:m.membership_date?.slice(0,10)||''});setModal(true)}
 async function save(e:any){e.preventDefault();try{editing?await api.updateMember(editing.id,form):await api.createMember(form);setModal(false);setEditing(null);setForm(blank);load()}catch(e:any){setError(e.message)}}
 async function deactivate(id:string){if(!confirm('Deactivate this member?'))return;try{await api.deactivateMember(id);load()}catch(e:any){setError(e.message)}}
 return <div><div className="mb-6 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h1 className="text-3xl font-bold">Members</h1><p className="text-slate-500">Manage your church membership directory.</p></div>{admin&&<button className="btn btn-primary" onClick={()=>{setEditing(null);setForm(blank);setModal(true)}}><Plus size={18}/>Add Member</button>}</div>
 {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}
 <div className="card mb-4 p-4 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="input pl-10" placeholder="Search members…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="input md:w-48" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
 <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Name</th><th className="p-4">Phone</th><th className="p-4">Email</th><th className="p-4">Status</th><th className="p-4">Membership Date</th><th className="p-4">Actions</th></tr></thead><tbody>{rows.map(m=><tr key={m.id} className="border-t"><td className="p-4 font-semibold">{m.first_name} {m.last_name}</td><td className="p-4">{m.phone||'—'}</td><td className="p-4">{m.email||'—'}</td><td className="p-4"><span className={`badge ${m.status==='active'?'bg-green-100 text-green-700':'bg-slate-100 text-slate-600'}`}>{m.status}</span></td><td className="p-4">{m.membership_date?.slice(0,10)}</td><td className="p-4"><div className="flex gap-1"><Link className="btn btn-secondary !px-2" to={`/members/${m.id}/attendance`} title="Attendance"><Eye size={16}/></Link>{admin&&<><button className="btn btn-secondary !px-2" onClick={()=>edit(m)}><Pencil size={16}/></button>{m.status==='active'&&<button className="btn btn-danger !px-2" onClick={()=>deactivate(m.id)}><UserX size={16}/></button>}</>}</div></td></tr>)}</tbody></table></div></div>
 {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={save} className="card max-h-[90vh] w-full max-w-2xl overflow-y-auto p-6"><h2 className="mb-5 text-xl font-bold">{editing?'Edit Member':'Add Member'}</h2><div className="grid gap-4 md:grid-cols-2">{[['first_name','First name'],['last_name','Last name'],['email','Email'],['phone','Phone'],['date_of_birth','Date of birth'],['membership_date','Membership date'],['gender','Gender']].map(([k,l])=><div key={k}><label className="label">{l}</label><input className="input" type={k.includes('date')?'date':k==='email'?'email':'text'} value={form[k]||''} required={k==='first_name'||k==='last_name'||k==='membership_date'} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="md:col-span-2"><label className="label">Address</label><textarea className="input" rows={3} value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></div></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn btn-primary">Save member</button></div></form></div>}
 </div>
}
